/* STREAMING_CHUNK:Initializing paths and configurations... */
/**
 * Dead by Daylight Random Roulette - Library Data
 * Full Integrated Data File
 */

const PATHS = { 
    PORTRAIT: 'images/killer_portrait/', 
    PERK_K: 'images/perk_killer/', 
    PERK_S: 'images/perk_survivor/', 
    ADDON: 'images/addons/', 
    ADDON_BG: 'images/addon_bg/' 
};

const rarityBgs = { 
    "common": "bg_common.webp", "uncommon": "bg_uncommon.webp", 
    "rare": "bg_rare.webp", "very_rare": "bg_very_rare.webp", "ultra_rare": "bg_ultra_rare.webp" 
};

/* STREAMING_CHUNK:Defining character lists... */
const killers = [
    { id: "trapper", name: "트래퍼" }, { id: "wraith", name: "레이스" }, { id: "hillbilly", name: "힐빌리" }, { id: "nurse", name: "너스" }, 
    { id: "shape", name: "쉐이프" }, { id: "hag", name: "해그" }, { id: "doctor", name: "닥터" }, { id: "huntress", name: "헌트리스" }, 
    { id: "cannibal", name: "카니발" }, { id: "nightmare", name: "나이트메어" }, { id: "pig", name: "피그" }, { id: "clown", name: "클라운" }, 
    { id: "spirit", name: "스피릿" }, { id: "legion", name: "군단" }, { id: "plague", name: "역병" }, { id: "ghostface", name: "고스트페이스" }, 
    { id: "demogorgon", name: "데모고르곤" }, { id: "oni", name: "악귀" }, { id: "deathslinger", name: "데스슬링거" }, { id: "executioner", name: "처형자" }, 
    { id: "blight", name: "블라이트" }, { id: "twins", name: "쌍둥이" }, { id: "trickster", name: "트릭스터" }, { id: "nemesis", name: "네메시스" }, 
    { id: "cenobite", name: "수도사" }, { id: "artist", name: "예술가" }, { id: "onryo", name: "원령" }, { id: "dredge", name: "드레지" }, 
    { id: "mastermind", name: "마스터마인드" }, { id: "knight", name: "기사" }, { id: "skullMerchant", name: "해골 상인" }, { id: "singularity", name: "특이점" }, 
    { id: "xenomorph", name: "제노모프" }, { id: "goodGuy", name: "착한 아이" }, { id: "unknown", name: "미지의 존재" }, { id: "lich", name: "리치" }, 
    { id: "darkLord", name: "어둠의 군주" }, { id: "houndmaster", name: "조련사" }, { id: "ghoul", name: "구울" }, { id: "animatronics", name: "애니매트로닉스" }, 
    { id: "ravenous", name: "끄라스" }, { id: "theFirst", name: "더 퍼스트" }, { id: "slasher", name: "슬래셔" }
];

const survivors = [
    { id: "dwight", name: "드와이트" }, { id: "meg", name: "메그" }, { id: "claudette", name: "클로뎃" }, { id: "jake", name: "제이크" },
    { id: "nea", name: "니아" }, { id: "ace", name: "에이스" }, { id: "feng", name: "펭 민" }, { id: "david", name: "데이비드" },
    { id: "jeff", name: "제프" }, { id: "jane", name: "제인" }, { id: "yui", name: "유이" }, { id: "zarina", name: "자리나" },
    { id: "felix", name: "펠릭스" }, { id: "elodie", name: "엘로디" }, { id: "yunjin", name: "이윤진" }, { id: "mikaela", name: "미카엘라" },
    { id: "jonah", name: "요나" }, { id: "haddie", name: "해디" }, { id: "vittorio", name: "비토리오" }, { id: "thalita", name: "탈리타" },
    { id: "renato", name: "헤나토" }, { id: "gabriel", name: "가브리엘" }, { id: "sable", name: "세이블" }, { id: "aestri", name: "에스트리" },
    { id: "shane_w", name: "셰인 위그와스" },
    { id: "laurie", name: "로리 스트로드" }, { id: "bill", name: "빌 오버벡" }, { id: "quentin", name: "쿠엔틴 스미스" }, { id: "tapp", name: "탭 형사" },
    { id: "ash", name: "애쉬 윌리엄스" }, { id: "steve", name: "스티브 해링턴" }, { id: "nancy", name: "낸시 휠러" }, { id: "cheryl", name: "쉐릴 메이슨" },
    { id: "leon", name: "레온 S. 케네디" }, { id: "jill", name: "질 발렌타인" }, { id: "yoichi", name: "요이치 아사카와" }, { id: "ada", name: "에이다 웡" },
    { id: "rebecca", name: "레베카 체임버스" }, { id: "cage", name: "니콜라스 케이지" }, { id: "ripley", name: "엘런 리플리" }, { id: "alan", name: "앨런 웨이크" },
    { id: "aestri_lic", name: "아스트리 야자르" }, { id: "lara", name: "라라 크로프트" }, { id: "trevor", name: "트레버 벨몬트" }
];

/* STREAMING_CHUNK:Defining killer perks... */
const killerPerkData = [
    { name: "주술: 죽음의 대한 공포", file: "hexScaredToDeath.webp", category: "슬래셔" },
    { name: "고요한 그림자", file: "silentShadow.webp", category: "슬래셔" },
    { name: "난동", file: "rampage.webp", category: "슬래셔" },
    { name: "시간 여행", file: "turnBackTheClock.webp", category: "역병" },
    { name: "비밀 프로젝트", file: "secretProject.webp", category: "닥터" },
    { name: "주술: 하이브 마인드", file: "hexHiveMind.webp", category: "해그" },
    { name: "격렬한 중얼거림", file: "bitterMurmur.webp", category: "공용 퍽" }, { name: "사슴 사냥꾼", file: "deerstalker.webp", category: "공용 퍽" },
    { name: "비참함", file: "distressing.webp", category: "공용 퍽" }, { name: "주술: 피할 수 없는 죽음", file: "hexNoOneEscapesDeath.webp", category: "공용 퍽" },
    { name: "주술: 사냥의 전율", file: "hexThrillOfTheHunt.webp", category: "공용 퍽" }, { name: "기만", file: "insidious.webp", category: "공용 퍽" },
    { name: "강철의 손아귀", file: "ironGrasp.webp", category: "공용 퍽" }, { name: "조각난 희망", file: "shatteredHope.webp", category: "공용 퍽" },
    { name: "악독한 도살자", file: "sloppyButcher.webp", category: "공용 퍽" }, { name: "어둠 속의 첩자", file: "spiesFromTheShadows.webp", category: "공용 퍽" },
    { name: "가차 없는 공격", file: "unrelenting.webp", category: "공용 퍽" }, { name: "속삭임", file: "whispers.webp", category: "공용 퍽" },
    { name: "재앙: 거대한 신전", file: "scourgeHookMonstrousShrine.webp", category: "공용 퍽" }, { name: "모든 수단을 동원", file: "noHoldsBarred.webp", category: "공용 퍽" },
    { name: "주술: 운명의 노리개", file: "hexFortunesFool.webp", category: "공용 퍽" }, { name: "재앙: 진물의 상처", file: "scourgeHookWeepingWounds.webp", category: "공용 퍽" },
    { name: "불안한 존재", file: "unnervingPresence.webp", category: "트래퍼" }, { name: "짐승 같은 힘", file: "brutalStrength.webp", category: "트래퍼" },
    { name: "동요", file: "agitation.webp", category: "트래퍼" }, { name: "포식자", file: "predator.webp", category: "레이스" },
    { name: "집요한 사냥개", file: "bloodhound.webp", category: "레이스" }, { name: "그림자의 피조물", file: "shadowborn.webp", category: "레이스" },
    { name: "인내심", file: "enduring.webp", category: "힐빌리" }, { name: "빛의 피조물", file: "lightborn.webp", category: "힐빌리" },
    { name: "땜장이", file: "tinkerer.webp", category: "힐빌리" }, { name: "천식", file: "stridor.webp", category: "너스" },
    { name: "사망 공포증", file: "thanatophobia.webp", category: "너스" }, { name: "간호사의 소명", file: "aNursesCalling.webp", category: "너스" },
    { name: "주술: 제3의 봉인", file: "hexTheThirdSeal.webp", category: "해그" }, { name: "주술: 파멸", file: "hexRuin.webp", category: "해그" },
    { name: "주술: 삼켜지는 희망", file: "hexDevourHope.webp", category: "해그" }, { name: "압도적인 존재감", file: "overwhelmingPresence.webp", category: "닥터" },
    { name: "감시와 학대", file: "monitorAndAbuse.webp", category: "닥터" }, { name: "과충전", file: "overcharge.webp", category: "닥터" },
    { name: "맹수", file: "beastOfPrey.webp", category: "헌트리스" }, { name: "텃세", file: "territorialImperative.webp", category: "헌트리스" },
    { name: "주술: 사냥꾼의 자장가", file: "hexHuntressLullaby.webp", category: "헌트리스" }, { name: "눈속임", file: "bamboozle.webp", category: "클라운" },
    { name: "광대 공포증", file: "coulrophobia.webp", category: "클라운" }, { name: "깜짝 상자", file: "popGoesTheWeasel.webp", category: "클라운" },
    { name: "분노의 영혼", file: "spiritFury.webp", category: "스피릿" }, { name: "주술: 원혼이 깃든 대지", file: "hexHauntedGround.webp", category: "스피릿" },
    { name: "원한", file: "rancor.webp", category: "스피릿" }, { name: "불협화음", file: "discordance.webp", category: "군단" },
    { name: "미친 투지", file: "madGrit.webp", category: "군단" }, { name: "아이언 메이든", file: "ironMaiden.webp", category: "군단" },
    { name: "부정한 개입", file: "corruptIntervention.webp", category: "역병" }, { name: "전염성 공포", file: "infectiousFright.webp", category: "역병" },
    { name: "어둠의 헌신", file: "darkDevotion.webp", category: "역병" }, { name: "잔심 전술", file: "zanshinTactics.webp", category: "악귀" },
    { name: "피의 메아리", file: "bloodEcho.webp", category: "악귀" }, { name: "천벌", file: "nemesis.webp", category: "악귀" },
    { name: "기어 헤드", file: "gearhead.webp", category: "데스슬링거" }, { name: "차단 스위치", file: "deadMansSwitch.webp", category: "데스슬링거" },
    { name: "주술: 응징", file: "hexRetribution.webp", category: "데스슬링거" }, { name: "드래곤의 손아귀", file: "dragonsGrip.webp", category: "블라이트" },
    { name: "주술: 피의 호의", file: "hexBloodFavour.webp", category: "블라이트" }, { name: "주술: 불멸", file: "hexUndying.webp", category: "블라이트" },
    { name: "호더", file: "hoarder.webp", category: "쌍둥이" }, { name: "억압", file: "oppression.webp", category: "쌍둥이" },
    { name: "최후의 일격", file: "coupDeGrace.webp", category: "쌍둥이" }, { name: "덕통사고", file: "starstruck.webp", category: "트릭스터" },
    { name: "주술: 군중 통제", file: "hexCrowdControl.webp", category: "트릭스터" }, { name: "출구 없음", file: "noWayOut.webp", category: "트릭스터" },
    { name: "암울한 수용", file: "grimEmbrace.webp", category: "예술가" }, { name: "재앙: 고통의 울림", file: "scourgeHookPainResonance.webp", category: "예술가" },
    { name: "주술: 펜티멘토", file: "hexPentimento.webp", category: "예술가" }, { name: "소멸", file: "dissolution.webp", category: "드레지" },
    { name: "드러난 어둠", file: "darknessRevealed.webp", category: "드레지" }, { name: "패혈성 손길", file: "septicTouch.webp", category: "드레지" },
    { name: "숨을 곳 없음", file: "nowhereToHide.webp", category: "기사" }, { name: "주술: 어둠을 마주하라", file: "hexFaceTheDarkness.webp", category: "기사" },
    { name: "자만심", file: "hubris.webp", category: "기사" }, { name: "강타!", file: "thwack.webp", category: "해골 상인" },
    { name: "레버리지", file: "leverage.webp", category: "해골 상인" }, { name: "시작된 게임", file: "gameAfoot.webp", category: "해골 상인" },
    { name: "유전학적 한계", file: "geneticLimits.webp", category: "특이점" }, { name: "강압 받은 망설임", file: "forcedHesitation.webp", category: "특이점" },
    { name: "머신 러닝", file: "machineLearning.webp", category: "특이점" }, { name: "해방", file: "unbound.webp", category: "미지의 존재" },
    { name: "불의", file: "unforeseen.webp", category: "미지의 존재" }, { name: "대실패", file: "undone.webp", category: "미지의 존재" },
    { name: "흔들리는 천둥", file: "allShakingThunder.webp", category: "조련사" }, { name: "재앙: 들쭉날쭉한 나침반", file: "scourgeHookJaggedCompass.webp", category: "조련사" },
    { name: "인정사정없이", file: "noQuarter.webp", category: "조련사" }, { name: "굶주림", file: "ravenous.webp", category: "끄라스" },
    { name: "방황하는 눈빛", file: "wanderingEye.webp", category: "끄라스" }, { name: "주술: 파멸의 서곡", file: "hexOvertureOfDoom.webp", category: "끄라스" },
    { name: "가장 좋은 것은 마지막에", file: "saveTheBestForLast.webp", category: "쉐이프" }, { name: "먹이 농락", file: "playWithYourFood.webp", category: "쉐이프" },
    { name: "꺼져 가는 빛", file: "dyingLight.webp", category: "쉐이프" }, { name: "때려눕히기", file: "knockOut.webp", category: "카니발" },
    { name: "바비큐 & 칠리", file: "barbecueAndChilli.webp", category: "카니발" }, { name: "프랭클린의 죽음", file: "franklinsDemise.webp", category: "카니발" },
    { name: "격분", file: "fireUp.webp", category: "나이트메어" }, { name: "나를 기억하나", file: "rememberMe.webp", category: "나이트메어" },
    { name: "피의 교도관", file: "bloodWarden.webp", category: "나이트메어" }, { name: "재앙: 집행인의 손재주", file: "scourgeHookHangmansTrick.webp", category: "피그" },
    { name: "감시", file: "surveillance.webp", category: "피그" }, { name: "선택하라", file: "makeYourChoice.webp", category: "피그" },
    { name: "밝은 귀", file: "imAllEars.webp", category: "고스트페이스" }, { name: "전율의 기쁨", file: "thrillingTremors.webp", category: "고스트페이스" },
    { name: "은밀한 추격", file: "furtiveChase.webp", category: "고스트페이스" }, { name: "서지", file: "surge.webp", category: "데모고르곤" },
    { name: "마인드 브레이커", file: "mindbreaker.webp", category: "데모고르곤" }, { name: "잔혹한 속박", file: "cruelLimits.webp", category: "데모고르곤" },
    { name: "강압 받은 속죄", file: "forcedPenance.webp", category: "처형자" }, { name: "고통의 흔적", file: "trailOfTorment.webp", category: "처형자" },
    { name: "죽음 결속", file: "deathbound.webp", category: "처형자" }, { name: "치명적인 추적자", file: "lethalPursuer.webp", category: "네메시스" },
    { name: "히스테리", file: "hysteria.webp", category: "네메시스" }, { name: "폭발", file: "eruption.webp", category: "네메시스" },
    { name: "교착 상태", file: "deadlock.webp", category: "수도사" }, { name: "주술: 노리개", file: "hexPlaything.webp", category: "수도사" },
    { name: "재앙: 고통의 선물", file: "scourgeHookGiftOfPain.webp", category: "수도사" }, { name: "재앙: 분노의 홍수", file: "scourgeHookFloodsOfRage.webp", category: "원령" },
    { name: "소금물의 부름", file: "callOfBrine.webp", category: "원령" }, { name: "무자비한 태풍", file: "mercilessStorm.webp", category: "원령" },
    { name: "우월한 신체", file: "superiorAnatomy.webp", category: "마스터마인드" }, { name: "깨어난 자각", file: "awakenedAwareness.webp", category: "마스터마인드" },
    { name: "종착역", file: "terminus.webp", category: "마스터마인드" }, { name: "궁극의 무기", file: "ultimateWeapon.webp", category: "제노모프" },
    { name: "빠른 잔혹함", file: "rapidBrutality.webp", category: "제노모프" }, { name: "에이리언의 직감", file: "alienInstinct.webp", category: "제노모프" },
    { name: "주술: 같이 놀자", file: "hexTwoCanPlay.webp", category: "착한 아이" }, { name: "영원한 친구", file: "friendsTilTheEnd.webp", category: "착한 아이" },
    { name: "건전지 포함", file: "batteriesIncluded.webp", category: "착한 아이" }, { name: "조율 엮기", file: "weaveAttunement.webp", category: "리치" },
    { name: "힘없는 손길", file: "languidTouch.webp", category: "리치" }, { name: "어둠의 오만함", file: "darkArrogance.webp", category: "리치" },
    { name: "주술: 비참한 운명", file: "hexWretchedFate.webp", category: "어둠의 군주" }, { name: "인간의 탐욕", file: "humanGreed.webp", category: "어둠의 군주" },
    { name: "권세", file: "dominance.webp", category: "어둠의 군주" }, { name: "주술: 비참함 그 자체", file: "hexNothingButMisery.webp", category: "구울" },
    { name: "영결의 뒤얽힘", file: "foreverEntwined.webp", category: "구울" }, { name: "아무도 자유롭지 않다", file: "noneAreFree.webp", category: "구울" },
    { name: "구인", file: "helpWanted.webp", category: "애니매트로닉스" }, { name: "유령 공포", file: "phantomFear.webp", category: "애니매트로닉스" },
    { name: "통제불능", file: "haywire.webp", category: "애니매트로닉스" }
];

/* STREAMING_CHUNK:Defining survivor perks... */
const survivorPerkData = [
    { name: "반대심문", file: "crossExamination.webp", category: "셰인 위그와스" },
    { name: "풀악셀", file: "wideOpenThrottle.webp", category: "셰인 위그와스" },
    { name: "도움의 손길", file: "lendaHand.webp", category: "셰인 위그와스" },
    { name: "몰입 상태", file: "flowState.webp", category: "권태영" }, { name: "우리만의 공간", file: "aPlaceForUs.webp", category: "권태영" }, { name: "5수 앞", file: "fiveMovesAhead.webp", category: "권태영" },
    { name: "기도: 거미줄치기", file: "invocationWeavingSpiders.webp", category: "세이블 와드" }, { name: "그림자의 힘", file: "strengthInShadows.webp", category: "세이블 와드" }, { name: "사악함", file: "wicked.webp", category: "세이블 와드" },
    { name: "음유시인의 영감", file: "bardicInspiration.webp", category: "아스트리 야자르" }, { name: "반사된 환영", file: "mirroredIllusion.webp", category: "아스트리 야자르" }, { name: "고요한 시선", file: "stillSight.webp", category: "아스트리 야자르" },
    { name: "바다 바다 붐", file: "badaBadaBoom.webp", category: "더스틴 핸더슨" }, { name: "계획 변경", file: "changeOfPlan.webp", category: "더스틴 핸더슨" }, { name: "팀워크: 풀 서킷", file: "teamworkFullCircuit.webp", category: "더스틴 핸더슨" },
    { name: "뛰어난 지각력", file: "extrasensoryPerception.webp", category: "일레븐" }, { name: "우리가 지켜보고 있다", file: "weSeeYou.webp", category: "일레븐" }, { name: "팀워크: 상냥한 사람", file: "teamworkSoftSpoken.webp", category: "일레븐" },
    { name: "경량화", file: "lightweight.webp", category: "공용 퍽" }, { name: "데자뷰", file: "dejaVu.webp", category: "공용 퍽" }, { name: "동질감", file: "kindred.webp", category: "공용 퍽" }, { name: "등골이 오싹해", file: "spineChill.webp", category: "공용 퍽" }, { name: "미끈한 고기", file: "slipperyMeat.webp", category: "공용 퍽" }, { name: "불길한 예감", file: "premonition.webp", category: "공용 퍽" }, { name: "아무도 버려두지 않아", file: "noOneLeftBehind.webp", category: "공용 퍽" }, { name: "약탈자의 본능", file: "plunderersInstinct.webp", category: "공용 퍽" }, { name: "어두운 감각", file: "darkSense.webp", category: "공용 퍽" }, { name: "우린 해낼거야", file: "wellMakeIt.webp", category: "공용 퍽" }, { name: "이런 일이 일어나다니", file: "thisIsNotHappening.webp", category: "공용 퍽" }, { name: "작은 사냥감", file: "smallGame.webp", category: "공용 퍽" }, { name: "회복력", file: "resilience.webp", category: "공용 퍽" }, { name: "희망", file: "hope.webp", category: "공용 퍽" },
    { name: "유대감", file: "bond.webp", category: "드와이트 페어필드" }, { name: "자기 증명", file: "proveThyself.webp", category: "드와이트 페어필드" }, { name: "리더", file: "leader.webp", category: "드와이트 페어필드" },
    { name: "빠르고 조용하게", file: "quickAndQuiet.webp", category: "메그 토마스" }, { name: "전력 질주", file: "sprintBurst.webp", category: "메그 토마스" }, { name: "아드레날린", file: "adrenaline.webp", category: "메그 토마스" },
    { name: "공감", file: "empathy.webp", category: "클로뎃 모렐" }, { name: "식물학 지식", file: "botanyKnowledge.webp", category: "클로뎃 모렐" }, { name: "자가 치료", file: "selfCare.webp", category: "클로뎃 모렐" },
    { name: "굳건한 의지", file: "ironWill.webp", category: "제이크 파크" }, { name: "차분한 영혼", file: "calmSpirit.webp", category: "제이크 파크" }, { name: "공작원", file: "saboteur.webp", category: "제이크 파크" },
    { name: "균형잡힌 착지", file: "balancedLanding.webp", category: "니어 칼슨" }, { name: "세련된 회피", file: "urbanEvasion.webp", category: "니어 칼슨" }, { name: "노련함", file: "streetwise.webp", category: "니어 칼슨" },
    { name: "통찰력", file: "openHanded.webp", category: "에이스 비스콘티" }, { name: "판돈 올리기", file: "upTheAnte.webp", category: "에이스 비스콘티" }, { name: "비장의 패", file: "aceInTheHole.webp", category: "에이스 비스콘티" },
    { name: "기술자", file: "technician.webp", category: "펭 민" }, { name: "유연함", file: "lithe.webp", category: "펭 민" }, { name: "기민함", file: "alert.webp", category: "펭 민" },
    { name: "우리는 영원히 살거야", file: "wereGonnaLiveForever.webp", category: "데이비드 킹" }, { name: "죽기살기", file: "deadHard.webp", category: "데이비드 킹" }, { name: "신경 쓰지 마", file: "noMither.webp", category: "데이비드 킹" },
    { name: "나와 함께 춤을", file: "danceWithMe.webp", category: "케이트 덴슨" }, { name: "기회의 창", file: "windowsOfOpportunity.webp", category: "케이트 덴슨" }, { name: "들끓는 화", file: "boilOver.webp", category: "케이트 덴슨" },
    { name: "교란", file: "diversion.webp", category: "아담 프란시스" }, { name: "구조", file: "deliverance.webp", category: "아담 프란시스" }, { name: "독학자", file: "autodidact.webp", category: "아담 프란시스" },
    { name: "부수기", file: "breakdown.webp", category: "제프 요한센" }, { name: "갱생 지도", file: "aftercare.webp", category: "제프 요한센" }, { name: "뒤틀림", file: "distortion.webp", category: "제프 요한센" },
    { name: "연대", file: "solidarity.webp", category: "제인 로메로" }, { name: "침착", file: "poised.webp", category: "제인 로메로" }, { name: "정면충돌", file: "headOn.webp", category: "제인 로메로" },
    { name: "행운", file: "luckyBreak.webp", category: "유이 키무라" }, { name: "필요하다면 무엇이든", file: "anyMeansNecessary.webp", category: "유이 키무라" }, { name: "탈출", file: "breakout.webp", category: "유이 키무라" },
    { name: "비공개 조건", file: "offTheRecord.webp", category: "자리나 카시르" }, { name: "오보", file: "redHerring.webp", category: "자리나 카시르" }, { name: "국민을 위하여", file: "forThePeople.webp", category: "자리나 카시르" },
    { name: "선견지명", file: "visionary.webp", category: "펠릭스 릭터" }, { name: "필사의 조치", file: "desperateMeasures.webp", category: "펠릭스 릭터" }, { name: "견고함", file: "builtToLast.webp", category: "펠릭스 릭터" },
    { name: "판단", file: "appraisal.webp", category: "엘로디 라코토" }, { name: "속임수", file: "deception.webp", category: "엘로디 라코토" }, { name: "힘찬 발버둥", file: "powerStruggle.webp", category: "엘로디 라코토" },
    { name: "고속 승진", file: "fastTrack.webp", category: "이윤진" }, { name: "대 히트", file: "smashHit.webp", category: "이윤진" }, { name: "자기 보호", file: "selfPreservation.webp", category: "이윤진" },
    { name: "예지력", file: "clairvoyance.webp", category: "미카엘라 레이드" }, { name: "호재: 치료의 순환", file: "boonCircleOfHealing.webp", category: "미카엘라 레이드" }, { name: "호재: 그림자 미행", file: "boonShadowStep.webp", category: "미카엘라 레이드" },
    { name: "극복", file: "overcome.webp", category: "요나 바스케스" }, { name: "교정 조치", file: "correctiveAction.webp", category: "요나 바스케스" }, { name: "호재: 지수", file: "boonExponential.webp", category: "요나 바스케스" },
    { name: "이너 포커스", file: "innerFocus.webp", category: "해디 카우르" }, { name: "남은 출현", file: "residualManifest.webp", category: "해디 카우르" }, { name: "지나친 열성", file: "overzealous.webp", category: "해디 카우르" },
    { name: "잠재 에너지", file: "potentialEnergy.webp", category: "비토리오 토스카노" }, { name: "안개에 관해서", file: "fogwise.webp", category: "비토리오 토스카노" }, { name: "빠른 포석", file: "quickGambit.webp", category: "비토리오 토스카노" },
    { name: "친선 경기", file: "friendlyCompetition.webp", category: "탈리타 리라" }, { name: "팀워크: 두 사람의 힘", file: "teamworkPowerOfTwo.webp", category: "탈리타 리라" }, { name: "제멋대로", file: "cutLoose.webp", category: "탈리타 리라" },
    { name: "블러드 러시", file: "bloodRush.webp", category: "헤나토 리라" }, { name: "팀워크: 단체 잠행", file: "teamworkCollectiveStealth.webp", category: "헤나토 리라" }, { name: "백그라운드 플레이어", file: "backgroundPlayer.webp", category: "헤나토 리라" },
    { name: "분쟁 조정자", file: "troubleshooter.webp", category: "가브리엘 소마" }, { name: "탄생의 목적", file: "madeForThis.webp", category: "가브리엘 소마" }, { name: "청소부", file: "scavenger.webp", category: "가브리엘 소마" },
    { name: "기도: 신뢰할 수 없는 까마귀", file: "invocationTreacherousCrows.webp", category: "타우리 카인" }, { name: "돌연 중단", file: "cleanBreak.webp", category: "타우리 카인" }, { name: "부담 감당", file: "shoulderTheBurden.webp", category: "타우리 카인" },
    { name: "무해함", file: "doNoHarm.webp", category: "오레라 로즈" }, { name: "주의의무", file: "dutyOfCare.webp", category: "오레라 로즈" }, { name: "신속 대응", file: "rapidResponse.webp", category: "오레라 로즈" },
    { name: "도로 위에 삶", file: "roadLife.webp", category: "뷔 분야삭" }, { name: "하나-둘-셋-넷!", file: "oneTwoThreeFour.webp", category: "뷔 분야삭" }, { name: "고스트 노트", file: "ghostNotes.webp", category: "뷔 분야삭" },
    { name: "유일한 생존자", file: "soleSurvivor.webp", category: "로리 스트로드" }, { name: "집착의 대상", file: "objectOfObsession.webp", category: "로리 스트로드" }, { name: "결정적인 일격", file: "decisiveStrike.webp", category: "로리 스트로드" },
    { name: "홀로 남겨진 자", file: "leftBehind.webp", category: "윌리엄 빌 오버벡" }, { name: "빌려온 시간", file: "borrowedTime.webp", category: "윌리엄 빌 오버벡" }, { name: "불굴", file: "unbreakable.webp", category: "윌리엄 빌 오버벡" },
    { name: "정신 차려!", file: "wakeUp.webp", category: "쿠엔틴 스미스" }, { name: "약제학", file: "pharmacy.webp", category: "쿠엔틴 스미스" }, { name: "불침번", file: "vigil.webp" , category: "쿠엔틴 스미스"},
    { name: "집념", file: "tenacity.webp", category: "탭 형사" }, { name: "형사의 직감", file: "detectivesHunch.webp", category: "탭 형사" }, { name: "잠복 근무", file: "stakeOut.webp", category: "탭 형사" },
    { name: "뒤집기", file: "flipFlop.webp", category: "애슐리 제이 윌리엄스" }, { name: "재정비", file: "buckleUp.webp", category: "애슐리 제이 윌리엄스" }, { name: "남자의 패기", file: "mettleOfMan.webp", category: "애슐리 제이 윌리엄스" },
    { name: "베이시터", file: "babysitter.webp", category: "스티브 해링턴" }, { name: "동료애", file: "camaraderie.webp", category: "스티브 해링턴" }, { name: "새로운 활력", file: "secondWind.webp", category: "스티브 해링턴" },
    { name: "함께라면 더 좋지", file: "betterTogether.webp", category: "낸시 휠러" }, { name: "시선 고정", file: "fixated.webp", category: "낸시 휠러" }, { name: "내면의 힘", file: "innerStrength.webp", category: "낸시 휠러" },
    { name: "소울 가드", file: "soulGuard.webp", category: "쉐릴 메이슨" }, { name: "피의 협정", file: "bloodPact.webp", category: "쉐릴 메이슨" }, { name: "억압된 동맹", file: "repressedAlliance.webp", category: "쉐릴 메이슨" },
    { name: "고통 참기", file: "biteTheBullet.webp", category: "레온 S. 케네디" }, { name: "섬광탄", file: "flashbang.webp", category: "레온 S. 케네디" }, { name: "신입의 패기", file: "rookieSpirit.webp", category: "레온 S. 케네디" },
    { name: "저항력", file: "counterforce.webp", category: "질 발렌타인" }, { name: "부활", file: "resurgence.webp", category: "질 발렌타인" }, { name: "폭풍형 지뢰", file: "blastMine.webp", category: "질 발렌타인" },
    { name: "보호자 지도", file: "parentalGuidance.webp", category: "요이치 아사카와" }, { name: "공감대 형성", file: "empathicConnection.webp", category: "요이치 아사카와" }, { name: "호재: 암흑 이론", file: "boonDarkTheory.webp", category: "요이치 아사카와" },
    { name: "도청 장치", file: "wiretap.webp", category: "에이다 웡" }, { name: "반응성 치료", file: "reactiveHealing.webp", category: "에이다 웡" }, { name: "낮은 관심", file: "lowProfile.webp" , category: "에이다 웡"},
    { name: "새것 보다 낫다", file: "betterThanNew.webp", category: "레베카 체임버스" }, { name: "안도감", file: "reassurance.webp", category: "레베카 체임버스" }, { name: "과집중", file: "hyperfocus.webp", category: "레베카 체임버스" },
    { name: "극작법", file: "dramaturgy.webp", category: "니콜라스 케이지" }, { name: "연기 파트너", file: "scenePartner.webp", category: "니콜라스 케이지" }, { name: "플롯 트위스트", file: "plotTwist.webp", category: "니콜라스 케이지" },
    { name: "럭키 스타", file: "luckyStar.webp", category: "엘런 리플리" }, { name: "화학물질 함정", file: "chemicalTrap.webp", category: "엘런 리플리" }, { name: "날렵함", file: "lightFooted.webp", category: "엘런 리플리" },
    { name: "호재: 조명", file: "boonIllumination.webp", category: "앨런 웨이크" }, { name: "빛의 챔피언", file: "championOfLight.webp", category: "앨런 웨이크" }, { name: "마감일", file: "deadline.webp", category: "앨런 웨이크" }
];

/* STREAMING_CHUNK:Defining tiers... */
const killerTiers = {
    5: ["깜짝 상자", "부정한 개입", "교착 상태", "재앙: 고통의 울림", "차단 스위치", "주술: 파멸", "시간 여행", "폭발", "주술: 사냥의 전율", "숨을 곳 없음"],
    4: ["바비큐 & 칠리", "최후의 일격", "프랭클린의 죽음", "암울한 수용", "눈속임", "밝은 귀", "출구 없음", "서지", "치명적인 추적자", "주술: 불멸", "주술: 피할 수 없는 죽음", "주술: 피의 호의", "주술: 하이브 마인드", "동요", "땜장이", "비밀 프로젝트", "간호사의 소명", "악독한 도살자", "주술: 펜티멘토", "불협화음", "감시와 학대", "가장 좋은 것은 마지막에", "마인드 브레이커", "권세", "난동"],
    3: ["어둠 속의 첩자", "주술: 삼켜지는 희망", "통제불능", "영원한 친구", "은밀한 추격", "소멸", "소금물의 부름", "재앙: 분노의 홍수", "드래곤의 손아귀", "인내심", "재앙: 고통의 선물", "전율의 기쁨", "재앙: 들쭉날쭉한 나침반", "주술: 군중 통제", "포식자", "빠른 잔혹함", "나를 기억하나", "무자비한 태풍", "전염성 공포", "선택하라", "감시", "원한", "천벌", "피의 교도관", "짐승 같은 힘", "속삭임", "광대 공포증", "주술: 원혼이 깃든 대지", "주술: 제3의 봉인", "아이언 메이든", "어둠의 헌신", "드러난 어둠", "주술: 어둠을 마주하라", "자만심", "강타!", "머신 러닝", "먹이 농락", "침묵의 그림자"],
    2: ["사슴 사냥꾼", "비참함", "기만", "강철의 손아귀", "가차 없는 공격", "재앙: 거대한 신전", "모든 수단을 동원", "주술: 운명의 노리개", "재앙: 진물의 상처", "불안한 존재", "집요한 사냥개", "그림자의 피조물", "빛의 피조물", "천식", "사망 공포증", "압도적인 존재감", "과충전", "맹수", "텃세", "주술: 사냥꾼의 자장가", "분노의 영혼", "미친 투지", "잔심 전술", "피의 메아리", "기어 헤드", "주술: 응징", "호더", "억압", "덕통사고", "패혈성 손길", "레버리지", "시작된 게임", "유전학적 한계", "강압 받은 망설임", "해방", "불의", "대실패", "흔들리는 천둥", "인정사정없이", "방황하는 눈빛", "꺼져 가는 빛", "때려눕히기", "격분", "재앙: 집행인의 손재주", "잔혹한 속박", "강압 받은 속죄", "고통의 흔적", "죽음 결속", "주술: 노리개", "우월한 신체", "깨어난 자각", "종착역", "궁극의 무기", "에이리언의 직감", "주술: 같이 놀자", "건전지 포함", "조율 엮기", "어둠의 오만함", "인간의 탐욕", "주술: 비참함 그 자체", "영결의 뒤얽힘"],
    1: ["조각난 희망", "격렬한 중얼거림", "굶주림", "주술: 파멸의 서곡", "힘없는 손길", "주술: 비참한 운명", "아무도 자유롭지 않다", "구인", "유령 공포", "주술: 죽음에 대한 공포"]
};

const survivorTiers = {
    5: ["전력 질주", "아드레날린", "회복력", "기회의 창", "죽기살기", "결정적인 일격", "비공개 조건", "데자뷰", "과집중", "안도감", "유연함", "5수 앞", "활짝 열린 스로틀"],
    4: ["유대감", "국민을 위하여", "뒤틀림", "날렵함", "불침번", "동질감", "우린 해낼거야", "극작법", "부활", "부담 감당", "베이시터", "내면의 힘", "빛의 챔피언", "탈출", "불굴", "균형잡힌 착지", "백그라운드 플레이어", "구출"],
    3: ["교란", "속임수", "플롯 트위스트", "반사된 환영", "음유시인의 영감", "하나-둘-셋-넷!", "차분한 영혼", "정면충돌", "공감", "우리는 영원히 살거야", "남자의 패기", "기민함", "자기 증명", "식물학 지식", "섬광탄", "화학물질 함정", "등골이 오싹해", "희망", "빠르고 조용하게", "블러드 러시", "리더", "호재: 치료의 순환", "어두운 감각", "반대 신문"],
    2: ["자가 치료", "극복", "빌려온 시간", "아무도 버려두지 않아", "대 히트", "고요한 시선", "경량화", "약탈자의 본능", "작은 사냥감", "굳건한 의지", "노련함", "통찰력", "기술자", "신경 쓰지 마", "나와 함께 춤을", "들끓는 화", "구조", "독학자", "부수기", "갱생 지도", "연대", "침착", "행운", "필요하다면 무엇이든", "오보", "선견지명", "필사의 조치", "견고함", "판단", "힘찬 발버둥", "고속 승진", "자기 보호", "예지력", "호재: 그림자 미행", "교정 조치", "호재: 지수", "이너 포커스", "남은 출현", "지나친 열성", "잠재 에너지", "안개에 관해서", "빠른 포석", "친선 경기", "team워크: 두 사람의 힘", "제멋대로", "team워크: 단체 잠행", "분쟁 조정자", "탄생의 목적", "청소부", "돌연 중단", "무해함", "주의의무", "신속 대응", "도로 위에 삶", "고스트 노트", "집착의 대상", "홀로 남겨진 자", "정신 차려!", "약제학", "집념", "형사의 직감", "잠복 근무", "뒤집기", "재정비", "동료애", "새로운 활력", "함께라면 더 좋지", "시선 고정", "소울 가드", "피의 협정", "억압된 동맹", "고통 참기", "폭풍형 지뢰", "보호자 지도", "공감대 형성", "호재: 암흑 이론", "도청 장치", "반응성 치료", "새것 보다 낫다", "연기 파트너", "럭키 스타", "호재: 조명", "마감일", "몰입 상태", "우리만의 공간", "그림자의 힘", "사악함", "바다 바다 붐", "계획 변경", "team워크: 풀 서킷", "뛰어난 지각력", "우리가 지켜보고 있다", "team워크: 상냥한 사람", "불길한 예감", "세련된 회피", "신입의 패기", "저항력", "도움의 손길"],
    1: ["기도: 거미줄치기", "기도: 신뢰할 수 없는 까마귀", "낮은 관심", "판돈 올리기", "미끈한 고기", "이런 일이 일어나다니", "유일한 생존자", "공작원"]
};

/* STREAMING_CHUNK:Defining killer addons... */
const killerAddons = {
    slasher: [
        { name: "휘어진 바퀴", file: "bentWheel.webp", rarity: "common" },
        { name: "정원용 발톱", file: "gardenClaw.webp", rarity: "common" },
        { name: "잡역부의 신발", file: "orderlysShoe.webp", rarity: "common" },
        { name: "뜨개질 바늘", file: "knittingNeedle.webp", rarity: "common" },
        { name: "피투성이 미소", file: "bloodySmile.webp", rarity: "uncommon" },
        { name: "파티 소음 발생기", file: "partyNoisemaker.webp", rarity: "uncommon" },
        { name: "침낭", file: "sleepingBag.webp", rarity: "uncommon" },
        { name: "유독성 폐기물", file: "toxicWaste.webp", rarity: "uncommon" },
        { name: "검시관의 커피", file: "coronersCoffee.webp", rarity: "uncommon" },
        { name: "사우나 스톤", file: "saunaRock.webp", rarity: "rare" },
        { name: "못 두 개", file: "twoNails.webp", rarity: "rare" },
        { name: "눈꼽", file: "eyeGoop.webp", rarity: "rare" },
        { name: "거울 조각", file: "mirrorShards.webp", rarity: "rare" },
        { name: "각인된 알루미늄", file: "imprintedAluminum.webp", rarity: "rare" },
        { name: "피투성이 탄창", file: "bloodyMagazine.webp", rarity: "very_rare" },
        { name: "타버린 퓨즈", file: "burntFuse.webp", rarity: "very_rare" },
        { name: "잃어버린 코르크 마개뽑이", file: "missingCorkscrew.webp", rarity: "very_rare" },
        { name: "보안관의 배지", file: "deputysBadge.webp", rarity: "very_rare" },
        { name: "더러운 돈", file: "dirtyMoney.webp", rarity: "ultra_rare" },
        { name: "핏빛 보트 모터", file: "iridescentBoatMotor.webp", rarity: "ultra_rare" }
    ],
    theFirst: [
        { name: "잡역부 ID", file: "orderlyID.webp", rarity: "common" },
        { name: "스테인드글라스 벽화", file: "stainedGlassMural.webp", rarity: "common" },
        { name: "산산조각난 손목 로켓", file: "shatteredWristRocket.webp", rarity: "common" },
        { name: "구슬 미로", file: "beadMaze.webp", rarity: "common" },
        { name: "피투성이 롤러스케이트", file: "bloodyRollerSkate.webp", rarity: "uncommon" },
        { name: "처참한 슈퍼컴", file: "guttedSupercom.webp", rarity: "uncommon" },
        { name: "시계 바늘", file: "clockHands.webp", rarity: "uncommon" },
        { name: "부서진 카세트 플레이어", file: "smashedCassetteDeck.webp", rarity: "uncommon" },
        { name: "미드센츄리 라디오", file: "midCenturyRadio.webp", rarity: "uncommon" },
        { name: "토끼 유골", file: "rabbitRemains.webp", rarity: "rare" },
        { name: "위조된 사망증명서", file: "forgedDeathCertificate.webp", rarity: "rare" },
        { name: "빅터의 면도날", file: "victorsRazorBlade.webp", rarity: "rare" },
        { name: "목 덩굴", file: "neckTendril.webp", rarity: "rare" },
        { name: "뇌파 캡", file: "electrodeCap.webp", rarity: "rare" },
        { name: "피자 고글", file: "pizzaGoggles.webp", rarity: "very_rare" },
        { name: "전기 충격 목줄", file: "electroshockCollar.webp", rarity: "very_rare" },
        { name: "블랙 위도우 거미", file: "blackWidowSpider.webp", rarity: "very_rare" },
        { name: "부서진 스케이트보드", file: "brokenSkateboard.webp", rarity: "very_rare" },
        { name: "핏빛 소테리아 칩", file: "iridescentSoteriaChip.webp", rarity: "ultra_rare" },
        { name: "체스말", file: "chessPiece.webp", rarity: "ultra_rare" }
    ],
    deathslinger: [
        { name: "손질용 걸레", file: "spitPolishRag.webp", rarity: "common" },
        { name: "뱀 기름", file: "snakeOil.webp", rarity: "common" },
        { name: "허술한 쇠사슬", file: "ricketyChain.webp", rarity: "common" },
        { name: "개조된 총알 벨트", file: "modifiedAmmoBelt.webp", rarity: "common" },
        { name: "녹슨 쇠말뚝", file: "rustedSpike.webp", rarity: "uncommon" },
        { name: "옻나무 잎", file: "poisonOakLeaves.webp", rarity: "uncommon" },
        { name: "보안관 배지", file: "marshalsBadge.webp", rarity: "uncommon" },
        { name: "조 스매셔", file: "jawSmasher.webp", rarity: "uncommon" },
        { name: "씹는 담배", file: "chewingTobacco.webp", rarity: "uncommon" },
        { name: "교도소장의 열쇠", file: "wardensKeys.webp", rarity: "rare" },
        { name: "현상수배 전단지", file: "wantedPoster.webp", rarity: "rare" },
        { name: "양철 기름통", file: "tinOilCan.webp", rarity: "rare" },
        { name: "주엽나무 가시덩굴", file: "honeyLocustThorn.webp", rarity: "rare" },
        { name: "감옥 쇠사슬", file: "prisonChain.webp", rarity: "very_rare" },
        { name: "골드 크리크 위스키", file: "goldCreekWhiskey.webp", rarity: "very_rare" },
        { name: "베이쇼어의 시가", file: "bayshoresCigar.webp", rarity: "very_rare" },
        { name: "철조망", file: "barbedWire.webp", rarity: "very_rare" },
        { name: "핏빛 동전", file: "iridescentCoin.webp", rarity: "ultra_rare" },
        { name: "헬셔 인두", file: "hellshireIron.webp", rarity: "ultra_rare" }
    ],
    executioner: [
        { name: "납 반지", file: "leadRing.webp", rarity: "common" },
        { name: "죽은 나비", file: "deadButterfly.webp", rarity: "common" },
        { name: "구리 반지", file: "copperRing.webp", rarity: "common" },
        { name: "검은 끈", file: "blackStrap.webp", rarity: "common" },
        { name: "밀랍 인형", file: "waxDoll.webp", rarity: "uncommon" },
        { name: "창 머리", file: "spearhead.webp", rarity: "uncommon" },
        { name: "표범 프린트 천", file: "leopardPrintFabric.webp", rarity: "uncommon" },
        { name: "잊혀진 비디오테이프", file: "forgottenVideotape.webp", rarity: "uncommon" },
        { name: "신데렐라의 오르골", file: "cinderellaMusicBox.webp", rarity: "uncommon" },
        { name: "발티엘 종파 사진", file: "valtielSectPhotograph.webp", rarity: "rare" },
        { name: "압박자의 판", file: "tabletoftheOppressor.webp", rarity: "rare" },
        { name: "안개 낀 날, 판결 후 남은 것", file: "mistyDayRemainsofJudgement.webp", rarity: "rare" },
        { name: "마네킹 발", file: "mannequinFoot.webp", rarity: "rare" },
        { name: "다홍색 알", file: "scarletEgg.webp", rarity: "very_rare" },
        { name: "녹슨색 알", file: "rustColouredEgg.webp", rarity: "very_rare" },
        { name: "잃어버린 기억의 책", file: "lostMemoriesBook.webp", rarity: "very_rare" },
        { name: "크림슨 세레모니 책", file: "crimsonCeremonyBook.webp", rarity: "very_rare" },
        { name: "흑요석 고블릿", file: "obsidianGoblet.webp", rarity: "ultra_rare" },
        { name: "핏빛 메타트론 큐브", file: "iridescentSealofMetatron.webp", rarity: "ultra_rare" }
    ],
    blight: [
        { name: "플라시보 약", file: "placeboTablet.webp", rarity: "common" },
        { name: "디기탈리스", file: "foxglove.webp", rarity: "common" },
        { name: "화합물 7", file: "compoundSeven.webp", rarity: "common" },
        { name: "닳아버린 단안경", file: "chippedMonocle.webp", rarity: "common" },
        { name: "뜯겨나간 노트", file: "shreddedNotes.webp", rarity: "uncommon" },
        { name: "고름집 가루", file: "pustulaDust.webp", rarity: "uncommon" },
        { name: "역병 담즙", file: "plagueBile.webp", rarity: "uncommon" },
        { name: "돌기 가시나무", file: "cankerThorn.webp", rarity: "uncommon" },
        { name: "골수", file: "boneMarrow.webp", rarity: "uncommon" },
        { name: "본영 소금", file: "umbraSalts.webp", rarity: "rare" },
        { name: "장미 강장제", file: "roseTonic.webp", rarity: "rare" },
        { name: "화합물 21", file: "compoundTwentyOne.webp", rarity: "rare" },
        { name: "황폐화된 까마귀", file: "blightedCrow.webp", rarity: "rare" },
        { name: "아드레날린 유리병", file: "adrenalineVial.webp", rarity: "rare" },
        { name: "비고의 일지", file: "vigosJournal.webp", rarity: "very_rare" },
        { name: "소환석", file: "summoningStone.webp", rarity: "very_rare" },
        { name: "영혼의 화학 물질", file: "soulChemical.webp", rarity: "very_rare" },
        { name: "연금술사의 반지", file: "alchemistsRing.webp", rarity: "very_rare" },
        { name: "핏빛 블라이트 태그", file: "iridescentBlightTag.webp", rarity: "ultra_rare" },
        { name: "화합물 33", file: "compoundThirtyThree.webp", rarity: "ultra_rare" }
    ],
    twins: [
        { name: "장난감 검", file: "toySword.webp", rarity: "common" },
        { name: "조그마한 손톱", file: "tinyFingernail.webp", rarity: "common" },
        { name: "산패된 우유", file: "souredMilk.webp", rarity: "common" },
        { name: "고양이 모형", file: "catFigurine.webp", rarity: "common" },
        { name: "마들렌의 장갑", file: "madeleinesGlove.webp", rarity: "uncommon" },
        { name: "의식용 나무 촛대", file: "ceremonialCandelabrum.webp", rarity: "uncommon" },
        { name: "고양이의 눈알", file: "catsEye.webp", rarity: "uncommon" },
        { name: "피투성이 검은 후드", file: "bloodyBlackHood.webp", rarity: "uncommon" },
        { name: "젖니", file: "babyTeeth.webp", rarity: "uncommon" },
        { name: "묵직한 딸랑이", file: "weightlyRattle.webp", rarity: "rare" },
        { name: "상한 비스킷", file: "staleBiscuit.webp", rarity: "rare" },
        { name: "하수구 진창", file: "sewerSludge.webp", rarity: "rare" },
        { name: "녹슨 바늘", file: "rustedNeedle.webp", rarity: "rare" },
        { name: "마들렌의 스카프", file: "madeleinesScarf.webp", rarity: "rare" },
        { name: "빅터의 병정", file: "victorsSoldier.webp", rarity: "very_rare" },
        { name: "팽이", file: "spinningTop.webp", rarity: "very_rare" },
        { name: "숲의 스튜", file: "forestStew.webp", rarity: "very_rare" },
        { name: "향수 한 방울", file: "dropofPerfume.webp", rarity: "very_rare" },
        { name: "입막이 천", file: "silencingCloth.webp", rarity: "ultra_rare" },
        { name: "핏빛 펜던트", file: "iridescentPendant.webp", rarity: "ultra_rare" }
    ],
    trickster: [
        { name: "트릭 주머니", file: "trickPouch.webp", rarity: "common" },
        { name: "메멘토 칼", file: "mementoBlades.webp", rarity: "common" },
        { name: "킬링 파트 선율", file: "killingPartChords.webp", rarity: "common" },
        { name: "지옥의 전선", file: "infernoWires.webp", rarity: "common" },
        { name: "테킬라 문락", file: "tequilaMoonrock.webp", rarity: "uncommon" },
        { name: "ON TARGET 싱글", file: "onTargetSingle.webp", rarity: "uncommon" },
        { name: "행운의 칼", file: "luckyBlade.webp", rarity: "uncommon" },
        { name: "지운의 사인", file: "jiWoonsAutograph.webp", rarity: "uncommon" },
        { name: "CAGED HEART 신발", file: "cagedHeartShoes.webp", rarity: "uncommon" },
        { name: "아름다운 선율의 살인", file: "melodiousMurder.webp", rarity: "rare" },
        { name: "WAITING FOR YOU 시계", file: "waitingForYouWatch.webp", rarity: "rare" },
        { name: "RIPPER 보호대", file: "ripperBrace.webp", rarity: "rare" },
        { name: "피즈-스핀 탄산음료", file: "fizzSpinSoda.webp", rarity: "rare" },
        { name: "피투성이 보아", file: "bloodyBoa.webp", rarity: "rare" },
        { name: "트릭 칼", file: "trickBlade.webp", rarity: "very_rare" },
        { name: "EDGE OF REVIVAL 앨범", file: "edgeOfRevivalAlbum.webp", rarity: "very_rare" },
        { name: "다이아몬드 커프링크", file: "diamondCufflinks.webp", rarity: "very_rare" },
        { name: "CUT THRU U 싱글", file: "cutThruUSingle.webp", rarity: "very_rare" },
        { name: "핏빛 포토 카드", file: "iridescentPhotocard.webp", rarity: "ultra_rare" },
        { name: "최후의 발악 컬렉션", file: "deathThoresCompilation.webp", rarity: "ultra_rare" }
    ],
    nemesis: [
        { name: "방문자 손목 밴드", file: "visitorWristband.webp", rarity: "common" },
        { name: "S.T.A.R.S. 전장 매뉴얼", file: "sTARSFieldManual.webp", rarity: "common" },
        { name: "손상된 주사기", file: "damagedSyringe.webp", rarity: "common" },
        { name: "브라이언의 창자", file: "briansIntestine.webp", rarity: "common" },
        { name: "좀비의 심장", file: "zombieHeart.webp", rarity: "uncommon" },
        { name: "미하일의 눈", file: "mikhailsEye.webp", rarity: "uncommon" },
        { name: "마빈의 피", file: "marvinsBlood.webp", rarity: "uncommon" },
        { name: "아드레날린 주사기", file: "adrenalineInjector.webp", rarity: "uncommon" },
        { name: "관리자 손목 밴드", file: "adminWristband.webp", rarity: "uncommon" },
        { name: "타이런트 고어", file: "tyrantGore.webp", rarity: "rare" },
        { name: "T-바이러스 샘플", file: "tVirusSample.webp", rarity: "rare" },
        { name: "세로토닌 주사기", file: "serotoninInjector.webp", rarity: "rare" },
        { name: "플랜트 43의 덩굴", file: "plant43Vines.webp", rarity: "rare" },
        { name: "릭커의 혀", file: "lickerTentacle.webp", rarity: "rare" },
        { name: "NE-알파 기생충", file: "nEAlphaParasite.webp", rarity: "very_rare" },
        { name: "질의 샌드위치", file: "jillsSandwich.webp", rarity: "very_rare" },
        { name: "감손된 잉크 리본", file: "depletedInkRibbon.webp", rarity: "very_rare" },
        { name: "부서진 회복 동전", file: "brokenRecoveryCoin.webp", rarity: "very_rare" },
        { name: "조각난 S.T.A.R.S. 배지", file: "shatteredSTARSBadge.webp", rarity: "ultra_rare" },
        { name: "핏빛 엄브렐러 배지", file: "iridescentUmbrellaBadge.webp", rarity: "ultra_rare" }
    ],
    cenobite: [
        { name: "가죽 조각", file: "leatherStrip.webp", rarity: "common" },
        { name: "구부러진 못", file: "bentNail.webp", rarity: "common" },
        { name: "타오르는 양초", file: "burningCandle.webp", rarity: "common" },
        { name: "활기 넘치는 귀뚜라미", file: "livelyCrickets.webp", rarity: "common" },
        { name: "깜빡거리는 텔레비전", file: "flickeringTelevision.webp", rarity: "uncommon" },
        { name: "꼬챙이에 찔린 쥐", file: "skeweredRat.webp", rarity: "uncommon" },
        { name: "꿈틀거리는 구더기", file: "wrigglingMaggots.webp", rarity: "uncommon" },
        { name: "상한 식사", file: "spoiledMeal.webp", rarity: "uncommon" },
        { name: "액화된 피곤죽", file: "liquifiedGore.webp", rarity: "uncommon" },
        { name: "고문 기둥", file: "torturePillar.webp", rarity: "rare" },
        { name: "래리의 유골", file: "larrysRemains.webp", rarity: "rare" },
        { name: "래리의 피", file: "larrysBlood.webp", rarity: "rare" },
        { name: "프랭크의 심장", file: "franksHeart.webp", rarity: "rare" },
        { name: "프랭크의 일부", file: "sliceofFrank.webp", rarity: "rare" },
        { name: "기름 낀 검은 렌즈", file: "greasyBlackLens.webp", rarity: "very_rare" },
        { name: "본연의 고통", file: "originalPain.webp", rarity: "very_rare" },
        { name: "살을 뚫은 철사", file: "impalingWire.webp", rarity: "very_rare" },
        { name: "채터러의 치아", file: "chatterersTooth.webp", rarity: "very_rare" },
        { name: "기술자의 이빨", file: "engineersFang.webp", rarity: "ultra_rare" },
        { name: "핏빛 비탄의 배열 장치", file: "iridescentLamentConfiguration.webp", rarity: "ultra_rare" }
    ],
    artist: [
        { name: "활기찬 부고 기사", file: "vibrantObituary.webp", rarity: "common" },
        { name: "걸쭉한 타르", file: "thickTar.webp", rarity: "common" },
        { name: "유화 물감", file: "oilPaints.webp", rarity: "common" },
        { name: "초클로 옥수수", file: "chocloCorn.webp", rarity: "common" },
        { name: "벨벳 천", file: "velvetFabric.webp", rarity: "uncommon" },
        { name: "무제의 고통", file: "untitledAgony.webp", rarity: "uncommon" },
        { name: "마음대로 그리기", file: "automaticDrawing.webp", rarity: "uncommon" },
        { name: "썩어가는 짐승 시체", file: "festeringCarrion.webp", rarity: "uncommon" },
        { name: "까마귀 정물화", file: "stillLifeCrow.webp", rarity: "uncommon" },
        { name: "가시돋친 둥지", file: "thornyNest.webp", rarity: "rare" },
        { name: "실버벨", file: "silverBell.webp", rarity: "rare" },
        { name: "슬픔이여, 사랑이여", file: "oGriefOLover.webp", rarity: "rare" },
        { name: "가장 어두운 잉크", file: "darkestInk.webp", rarity: "rare" },
        { name: "목탄 연필", file: "charcoalStick.webp", rarity: "rare" },
        { name: "잘린 혀", file: "severedTongue.webp", rarity: "very_rare" },
        { name: "잘린 손", file: "severedHands.webp", rarity: "very_rare" },
        { name: "마티아스의 아기 신발", file: "matiasBabyShoes.webp", rarity: "very_rare" },
        { name: "잉크 뭉침", file: "inkEgg.webp", rarity: "very_rare" },
        { name: "핏빛 깃털", file: "iridescentFeather.webp", rarity: "ultra_rare" },
        { name: "부패의 정원", file: "gardenofRot.webp", rarity: "ultra_rare" }
    ],
    onryo: [
        { name: "비디오테이프 사본", file: "videotapeCopy.webp", rarity: "common" },
        { name: "오래된 신문", file: "oldNewspaper.webp", rarity: "common" },
        { name: "어머니의 거울", file: "mothersMirror.webp", rarity: "common" },
        { name: "통나무집 표지판", file: "cabinSign.webp", rarity: "common" },
        { name: "요이치의 낚시 그물", file: "yoichisFishingNet.webp", rarity: "uncommon" },
        { name: "우물의 돌", file: "wellStone.webp", rarity: "uncommon" },
        { name: "바닷물 젖은 옷", file: "seaSoakedCloth.webp", rarity: "uncommon" },
        { name: "레이코의 시계", file: "reikosWatch.webp", rarity: "uncommon" },
        { name: "한줌의 머리카락", file: "clumpofHair.webp", rarity: "uncommon" },
        { name: "우물의 물", file: "wellWater.webp", rarity: "rare" },
        { name: "링 그림", file: "ringDrawing.webp", rarity: "rare" },
        { name: "부서질 듯한 바람개비", file: "ricketyPinwheel.webp", rarity: "rare" },
        { name: "어머니의 빗", file: "mothersComb.webp", rarity: "rare" },
        { name: "피투성이 손톱", file: "bloodyFingernails.webp", rarity: "rare" },
        { name: "비디오카세트 레코더", file: "vCR.webp", rarity: "very_rare" },
        { name: "전화기", file: "telephone.webp", rarity: "very_rare" },
        { name: "테이프 편집 컨트롤러", file: "tapeEditingDeck.webp", rarity: "very_rare" },
        { name: "왜곡된 사진", file: "distortedPhoto.webp", rarity: "very_rare" },
        { name: "리모컨", file: "remoteControl.webp", rarity: "ultra_rare" },
        { name: "핏빛 비디오테이프", file: "iridescentVideotape.webp", rarity: "ultra_rare" }
    ],
    dredge: [
        { name: "카페인 약", file: "caffeineTablets.webp", rarity: "common" },
        { name: "추종자들의 고깔", file: "followersCowl.webp", rarity: "common" },
        { name: "절구와 절구 공이", file: "mortarandPestel.webp", rarity: "common" },
        { name: "나무판자", file: "woodenPlank.webp", rarity: "common" },
        { name: "해디의 달력", file: "haddiesCalendar.webp", rarity: "uncommon" },
        { name: "불타버린 편지", file: "burntLetters.webp", rarity: "uncommon" },
        { name: "부정한 사상가의 두개골", file: "malthinkersSkull.webp", rarity: "uncommon" },
        { name: "방향제", file: "airFreshener.webp", rarity: "uncommon" },
        { name: "떨어진 지붕널", file: "fallenShingle.webp", rarity: "uncommon" },
        { name: "파괴된 베개", file: "destroyedPillow.webp", rarity: "rare" },
        { name: "전투모", file: "warHelmet.webp", rarity: "rare" },
        { name: "오토마리안의 글", file: "ottomarianWriting.webp", rarity: "rare" },
        { name: "망가진 인형", file: "brokenDoll.webp", rarity: "rare" },
        { name: "걱정의 돌", file: "worryStone.webp", rarity: "rare" },
        { name: "현장 녹화", file: "fieldRecorder.webp", rarity: "very_rare" },
        { name: "소형 마이크", file: "lavalierMicrophone.webp", rarity: "very_rare" },
        { name: "배 열쇠", file: "boatKey.webp", rarity: "very_rare" },
        { name: "밭 가는 칼날", file: "tillingBlade.webp", rarity: "very_rare" },
        { name: "희생의 칼", file: "sacrificialKnife.webp", rarity: "ultra_rare" },
        { name: "핏빛 나무판자", file: "iridescentWoodenPlank.webp", rarity: "ultra_rare" }
    ],
    mastermind: [
        { name: "비단벌레", file: "jewelBeetle.webp", rarity: "common" },
        { name: "우로보로스 덩굴", file: "uroborosTendril.webp", rarity: "common" },
        { name: "유니콘 메달", file: "unicornMedallion.webp", rarity: "common" },
        { name: "R.P.D. 어깨 무전기", file: "rPDShoulderWalkie.webp", rarity: "common" },
        { name: "느슨한 크랭크", file: "looseCrank.webp", rarity: "uncommon" },
        { name: "가죽 장갑", file: "leatherGloves.webp", rarity: "uncommon" },
        { name: "사자 메달", file: "lionMedallion.webp", rarity: "uncommon" },
        { name: "성배(황금)", file: "chaliceGold.webp", rarity: "uncommon" },
        { name: "확성기", file: "bullhorn.webp", rarity: "uncommon" },
        { name: "휴대용 금고", file: "portableSafe.webp", rarity: "rare" },
        { name: "레드 허브", file: "redHerb.webp", rarity: "rare" },
        { name: "소녀 메달", file: "maidenMedallion.webp", rarity: "rare" },
        { name: "화상회의 장치", file: "videoConferenceDevice.webp", rarity: "rare" },
        { name: "달걀(황금)", file: "eggGold.webp", rarity: "rare" },
        { name: "검은 선글라스", file: "darkSunglasses.webp", rarity: "very_rare" },
        { name: "헬리콥터 조종간", file: "helicopterStick.webp", rarity: "very_rare" },
        { name: "그린 허브", file: "greenHerb.webp", rarity: "very_rare" },
        { name: "우로보로스 바이러스", file: "uroborosVirus.webp", rarity: "very_rare" },
        { name: "연구소 사진", file: "labPhoto.webp", rarity: "ultra_rare" },
        { name: "핏빛 우로보로스 약병", file: "iridescentUrobosVial.webp", rarity: "ultra_rare" }
    ],
    knight: [
        { name: "낡은 타바드", file: "tatteredTabard.webp", rarity: "common" },
        { name: "약탈된 벌꿀 술", file: "pillagedMead.webp", rarity: "common" },
        { name: "영역의 지도", file: "mapoftheRealm.webp", rarity: "common" },
        { name: "모래 덩어리", file: "grittyLump.webp", rarity: "common" },
        { name: "버려진 칼날", file: "treatedBlade.webp", rarity: "uncommon" },
        { name: "말린 말고기", file: "driedHorsemeat.webp", rarity: "uncommon" },
        { name: "차가운 강철 수갑", file: "coldSteelManacles.webp", rarity: "uncommon" },
        { name: "군대 동원", file: "callToArms.webp", rarity: "uncommon" },
        { name: "큰 도끼의 도끼날", file: "battleAxeHead.webp", rarity: "uncommon" },
        { name: "방범대원의 횃불", file: "townWatchsTorch.webp", rarity: "rare" },
        { name: "철공의 집게", file: "ironworkersTongs.webp", rarity: "rare" },
        { name: "죽음의 철가면", file: "grimIronMask.webp", rarity: "rare" },
        { name: "날카로운 탈것", file: "sharpenedMount.webp", rarity: "rare" },
        { name: "깨진 검자루", file: "brokenHilt.webp", rarity: "rare" },
        { name: "교도소장의 차임", file: "jailersChimes.webp", rarity: "very_rare" },
        { name: "치료용 찜질", file: "healingPoultice.webp", rarity: "very_rare" },
        { name: "부싯돌과 강철", file: "flintandSteel.webp", rarity: "very_rare" },
        { name: "대장장이의 망치", file: "blacksmithsHammer.webp", rarity: "very_rare" },
        { name: "기사의 계약서", file: "knightsContract.webp", rarity: "ultra_rare" },
        { name: "핏빛 단체 배너", file: "iridescentCompanyBanner.webp", rarity: "ultra_rare" }
    ],
    skullMerchant: [
        { name: "초음파 덫 스피커", file: "ultrasonicTrapSpeaker.webp", rarity: "common" },
        { name: "아디 발렌테 1권", file: "adiValenteIssue1.webp", rarity: "common" },
        { name: "대전류 업그레이드", file: "highCurrentUpgrade.webp", rarity: "common" },
        { name: "고성능의 투광 조명등", file: "highPowerFloodlight.webp", rarity: "common" },
        { name: "적응형 조명", file: "adaptiveLightning.webp", rarity: "uncommon" },
        { name: "저전력 모드", file: "lowPowerMode.webp", rarity: "uncommon" },
        { name: "스테레오 원격 마이크", file: "stereoRemoteMic.webp", rarity: "uncommon" },
        { name: "샷건 스피커", file: "shotgunSpeakers.webp", rarity: "uncommon" },
        { name: "슈퍼차지", file: "supercharge.webp", rarity: "uncommon" },
        { name: "중요 타겟팅 프로세서", file: "vitalTargetingProcessor.webp", rarity: "rare" },
        { name: "적외선 업그레이드", file: "infraredUpgrade.webp", rarity: "rare" },
        { name: "유리 가루", file: "powderedGlass.webp", rarity: "rare" },
        { name: "느슨한 나사", file: "looseScrew.webp", rarity: "rare" },
        { name: "갈색 잡음 발생기", file: "brownNoiseGenerator.webp", rarity: "rare" },
        { name: "프로토타입 회전자", file: "prototypeRotor.webp", rarity: "very_rare" },
        { name: "지리적 판독", file: "geographicalReadout.webp", rarity: "very_rare" },
        { name: "무작위 섬광등", file: "randomisedStrobes.webp", rarity: "very_rare" },
        { name: "고기능 움직임 예측기", file: "advancedMovementPrediction.webp", rarity: "very_rare" },
        { name: "핏빛 미발행 원고", file: "iridescentUnpublishedManuscript.webp", rarity: "ultra_rare" },
        { name: "방전된 배터리", file: "expiredBatteries.webp", rarity: "ultra_rare" }
    ],
    singularity: [
        { name: "영양 가득한 슬러리", file: "nutritionalSlurry.webp", rarity: "common" },
        { name: "진단 도구(수리용)", file: "diagnosticToolRepair.webp", rarity: "common" },
        { name: "중수", file: "heavyWater.webp", rarity: "common" },
        { name: "부숴진 보안 열쇠", file: "brokenSecurityKey.webp", rarity: "common" },
        { name: "화장된 유골", file: "crematedRemains.webp", rarity: "uncommon" },
        { name: "크리오젤", file: "cryoGel.webp", rarity: "uncommon" },
        { name: "초음파 센서", file: "ultrasonicSensor.webp", rarity: "uncommon" },
        { name: "어린아이의 야구 글러브", file: "kidsBallGlove.webp", rarity: "uncommon" },
        { name: "안드로이드 팔", file: "androidArm.webp", rarity: "uncommon" },
        { name: "텅빈 산소 탱크", file: "spentOxygenTank.webp", rarity: "rare" },
        { name: "활선", file: "liveWires.webp", rarity: "rare" },
        { name: "홀로그램 발전기", file: "hologramGenerator.webp", rarity: "rare" },
        { name: "초자각 스프레이", file: "hyperawarenessSpray.webp", rarity: "rare" },
        { name: "나노 기기 젤", file: "nanomachineGel.webp", rarity: "rare" },
        { name: "외계 식물 섬유", file: "foreignPlantFibers.webp", rarity: "very_rare" },
        { name: "진단 도구(건설용)", file: "diagnosticToolConstruction.webp", rarity: "very_rare" },
        { name: "승조원 명단", file: "crewManifest.webp", rarity: "very_rare" },
        { name: "소마의 가족 사진", file: "somaFamilyPhoto.webp", rarity: "very_rare" },
        { name: "핏빛 크리스탈 파편", file: "iridescentCrystalShard.webp", rarity: "ultra_rare" },
        { name: "거부된 요청 방식", file: "deniedRequestingForm.webp", rarity: "ultra_rare" }
    ],
    xenomorph: [
        { name: "오보모프", file: "ovomorph.webp", rarity: "common" },
        { name: "시리얼 배급량", file: "cerealRations.webp", rarity: "common" },
        { name: "물먹는 새", file: "drinkingBird.webp", rarity: "common" },
        { name: "더블 디지털 시계", file: "ripleysWatch.webp", rarity: "common" },
        { name: "야광봉", file: "lightWand.webp", rarity: "uncommon" },
        { name: "애쉬의 내부", file: "ashsInnards.webp", rarity: "uncommon" },
        { name: "승무원 수신기", file: "crewHeadset.webp", rarity: "uncommon" },
        { name: "브렛의 모자", file: "brettsCap.webp", rarity: "uncommon" },
        { name: "램버트의 별자리표", file: "lambertsStarMap.webp", rarity: "uncommon" },
        { name: "파커의 머리띠", file: "parkersHeadband.webp", rarity: "rare" },
        { name: "케인의 헬멧", file: "kanesHelmet.webp", rarity: "rare" },
        { name: "제노모프 허물", file: "moultedSkin.webp", rarity: "rare" },
        { name: "작살 발사포", file: "harpoonGun.webp", rarity: "very_rare" },
        { name: "자폭 장치 볼트", file: "selfDestructBolt.webp", rarity: "very_rare" },
        { name: "기호학적 키보드", file: "semioticKeyboard.webp", rarity: "very_rare" },
        { name: "고양이 이동장", file: "catCarrier.webp", rarity: "very_rare" },
        { name: "핏빛 산성피", file: "acidicBlood.webp", rarity: "ultra_rare" },
        { name: "막 만든 소몰이 막대", file: "improvisedCattleProd.webp", rarity: "ultra_rare" }
    ],
    goodGuy: [
        { name: "착한 아이 인형 상자", file: "goodGuyBox.webp", rarity: "common" },
        { name: "작은 메스", file: "tinyScalpel.webp", rarity: "common" },
        { name: "인형의 눈", file: "dollEyes.webp", rarity: "common" },
        { name: "섬광등", file: "strobingLight.webp", rarity: "common" },
        { name: "헤어스프레이와 양초", file: "hairSprayCandle.webp", rarity: "uncommon" },
        { name: "줄넘기", file: "jumpRope.webp", rarity: "uncommon" },
        { name: "조각용 전기 나이프", file: "electricCarvingKnife.webp", rarity: "uncommon" },
        { name: "전동 드릴", file: "powerDrill.webp", rarity: "uncommon" },
        { name: "자동 드라이버", file: "automaticScrewdriver.webp", rarity: "uncommon" },
        { name: "휴대용 TV", file: "portableTV.webp", rarity: "rare" },
        { name: "쥐약", file: "ratPoison.webp", rarity: "rare" },
        { name: "야드 자", file: "yardstick.webp", rarity: "rare" },
        { name: "실크 베개", file: "silkPillow.webp", rarity: "rare" },
        { name: "러닝화", file: "runningShoes.webp", rarity: "rare" },
        { name: "비닐 봉지", file: "plasticBag.webp", rarity: "very_rare" },
        { name: "못 더미", file: "pileofNails.webp", rarity: "very_rare" },
        { name: "면도칼", file: "straightRazor.webp", rarity: "very_rare" },
        { name: "거울 조각", file: "mirrorShards.webp", rarity: "very_rare" },
        { name: "안전모", file: "hardHat.webp", rarity: "ultra_rare" },
        { name: "무지개빛 부적", file: "iridescentAmulet.webp", rarity: "ultra_rare" }
    ],
    unknown: [
        { name: "흐릿한 사진", file: "blurryPhoto.webp", rarity: "common" },
        { name: "토끼의 발", file: "rabbitsFoot.webp", rarity: "common" },
        { name: "그림 그리기", file: "sketchAttempt.webp", rarity: "common" },
        { name: "구멍 뚫린 안구", file: "puncturedEyeball.webp", rarity: "common" },
        { name: "피해자의 지도", file: "victimsMap.webp", rarity: "uncommon" },
        { name: "출처 불명의 기기", file: "deviceofUndisclosedOrigin.webp", rarity: "uncommon" },
        { name: "이론 노트", file: "noteofTheories.webp", rarity: "uncommon" },
        { name: "마지막으로 알려진 녹음 파일", file: "lastKnownRecording.webp", rarity: "uncommon" },
        { name: "길게 그인 백팩", file: "slashedBackpack.webp", rarity: "uncommon" },
        { name: "최면술사의 시계", file: "hypnotistsWatch.webp", rarity: "rare" },
        { name: "신문 1면", file: "frontPageArticle.webp", rarity: "rare" },
        { name: "사라지는 상자", file: "vanishingBox.webp", rarity: "rare" },
        { name: "발자국 주물", file: "footprintCast.webp", rarity: "rare" },
        { name: "B급 영화 포스터", file: "bMoviePoster.webp", rarity: "rare" },
        { name: "수제 가면", file: "homemadeMask.webp", rarity: "very_rare" },
        { name: "세럼병", file: "serumVial.webp", rarity: "very_rare" },
        { name: "버려진 우유 상자", file: "discardedMilkCarton.webp", rarity: "very_rare" },
        { name: "모호한 게임 카트리지", file: "obscureGameCartridge.webp", rarity: "very_rare" },
        { name: "핏빛 OSS 보고서", file: "iridescentOSSReport.webp", rarity: "ultra_rare" },
        { name: "어둠에 사로잡히다", file: "capturedbytheDark.webp", rarity: "ultra_rare" }
    ],
    houndmaster: [
        { name: "덜 익은 코코넛", file: "youngCoconut.webp", rarity: "common" },
        { name: "훈련사의 책자", file: "trainersBook.webp", rarity: "common" },
        { name: "끈적한 공", file: "stickyPitch.webp", rarity: "common" },
        { name: "생명체의 뼈", file: "creaturesBone.webp", rarity: "common" },
        { name: "훈제 생선", file: "smokedSnapper.webp", rarity: "uncommon" },
        { name: "매듭을 지은 로프", file: "knottedRope.webp", rarity: "uncommon" },
        { name: "밧줄걸이", file: "belayingPins.webp", rarity: "uncommon" },
        { name: "작은 망원경", file: "spyglass.webp", rarity: "uncommon" },
        { name: "보리를 으깬 곡물", file: "barleyMeal.webp", rarity: "uncommon" },
        { name: "수통", file: "waterskin.webp", rarity: "rare" },
        { name: "미완성 지도", file: "unfinishedMap.webp", rarity: "rare" },
        { name: "훈련용 종", file: "trainingBell.webp", rarity: "rare" },
        { name: "스파이크가 박힌 칼라", file: "spikedCollar.webp", rarity: "rare" },
        { name: "기름진 고기", file: "fattyMeat.webp", rarity: "rare" },
        { name: "배 선수상", file: "shipFigurehead.webp", rarity: "very_rare" },
        { name: "밧줄 스파이크", file: "marlinspike.webp", rarity: "very_rare" },
        { name: "가죽 하네스", file: "leatherHarness.webp", rarity: "very_rare" },
        { name: "화약통", file: "gunpowderTin.webp", rarity: "very_rare" },
        { name: "찢겨진 소설", file: "tornNovel.webp", rarity: "ultra_rare" },
        { name: "핏빛 선박 키", file: "iridescentWheelHandle.webp", rarity: "ultra_rare" }
    ],
    ravenous: [
        { name: "끈적한 목캔디", file: "stickyLozenge.webp", rarity: "common" },
        { name: "부서진 티아라", file: "brokenTiara.webp", rarity: "common" },
        { name: "재수 옴 붙은 쥐", file: "lucklessMouse.webp", rarity: "common" },
        { name: "첫 번째 오페라의 대본", file: "firstLibretto.webp", rarity: "common" },
        { name: "결함 있는 메트로놈", file: "defectiveMetronome.webp", rarity: "uncommon" },
        { name: "구겨진 악보", file: "crumpledSheetMusic.webp", rarity: "uncommon" },
        { name: "꿈틀거리는 기생충", file: "wrigglingParasite.webp", rarity: "uncommon" },
        { name: "돼지의 눈", file: "pigsEye.webp", rarity: "uncommon" },
        { name: "말라이의 덩어리", file: "chunkOfMalai.webp", rarity: "uncommon" },
        { name: "무딘 칼", file: "dulledKnife.webp", rarity: "rare" },
        { name: "액자에 걸린 신문", file: "framedNewspaper.webp", rarity: "rare" },
        { name: "얼룩진 손수건", file: "spatteredHandkerchief.webp", rarity: "rare" },
        { name: "오페라 글라스", file: "theaterBinoculars.webp", rarity: "rare" },
        { name: "잔지라의 손", file: "janjirasHand.webp", rarity: "rare" },
        { name: "로렌자의 유골", file: "lorenzasRemains.webp", rarity: "very_rare" },
        { name: "썩은 돼지", file: "rottenSwine.webp", rarity: "very_rare" },
        { name: "여왕의 홀", file: "queensScepter.webp", rarity: "very_rare" },
        { name: "핏빛 묘약", file: "iridescentElixir.webp", rarity: "very_rare" },
        { name: "닭머리", file: "chickenHead.webp", rarity: "ultra_rare" },
        { name: "잘게 조각난 가운", file: "shreddedGown.webp", rarity: "ultra_rare" }
    ],
    animatronics: [
        { name: "기름 가득한 종이 접시", file: "greasyPaperPlate.webp", rarity: "common" },
        { name: "구인 광고", file: "helpWantedAD.webp", rarity: "common" },
        { name: "레스토랑 메뉴", file: "restaurantMenu.webp", rarity: "common" },
        { name: "상한 피자", file: "rottenPizza.webp", rarity: "common" },
        { name: "피자 포장끈", file: "streamers.webp", rarity: "uncommon" },
        { name: "경비원의 배지", file: "securityGuardsBadge.webp", rarity: "uncommon" },
        { name: "찢어진 커튼", file: "rippedCurtain.webp", rarity: "uncommon" },
        { name: "파티용 모자", file: "partyHat.webp", rarity: "uncommon" },
        { name: "사무실 전화기", file: "officePhone.webp", rarity: "uncommon" },
        { name: "보니의 기타줄", file: "bonniesGuitarStrings.webp", rarity: "rare" },
        { name: "치카의 턱받이", file: "chicasBib.webp", rarity: "rare" },
        { name: "폭시의 갈고리", file: "foxysHook.webp", rarity: "rare" },
        { name: "프레디의 모자", file: "freddysHat.webp", rarity: "rare" },
        { name: "퍼플가이의 그림", file: "purpleGuyDrawing.webp", rarity: "rare" },
        { name: "전리품 가방", file: "lootBag.webp", rarity: "very_rare" },
        { name: "내장 CPU", file: "endoCPU.webp", rarity: "very_rare" },
        { name: "축제! 포스터", file: "celebratePoster.webp", rarity: "very_rare" },
        { name: "컨트롤패널 접근", file: "accessPanel.webp", rarity: "very_rare" },
        { name: "핏빛 잔류물", file: "iridescentRemnant.webp", rarity: "ultra_rare" },
        { name: "파즈코인", file: "fazCoin.webp", rarity: "ultra_rare" }
    ],
    ghoul: [
        { name: "검은 산양의 알", file: "theBlackGoatsEgg.webp", rarity: "common" },
        { name: "붕어빵", file: "taiyaki.webp", rarity: "common" },
        { name: "안테이크 앞치마", file: "anteikuApron.webp", rarity: "common" },
        { name: "카네키의 지갑", file: "kanekisWallet.webp", rarity: "common" },
        { name: "히나미의 우산", file: "hinamisUmbrella.webp", rarity: "uncommon" },
        { name: "브로큰 체인", file: "brokenChain.webp", rarity: "uncommon" },
        { name: "카네키의 배낭", file: "kanekisSatchel.webp", rarity: "uncommon" },
        { name: "피로 얼룩진 손수건", file: "bloodStainedHandkerchief.webp", rarity: "uncommon" },
        { name: "히데의 헤드폰", file: "hidesHeadphones.webp", rarity: "uncommon" },
        { name: "리제의 안경", file: "rizesGlasses.webp", rarity: "rare" },
        { name: "마도의 장갑", file: "madosGlove.webp", rarity: "rare" },
        { name: "아몬의 넥타이", file: "amonsNecktie.webp", rarity: "rare" },
        { name: "아오기리 나무 로브", file: "aogiriTreeRobe.webp", rarity: "rare" },
        { name: "붉은 거미 백합", file: "redSpiderLily.webp", rarity: "rare" },
        { name: "신선한 커피", file: "freshCoffee.webp", rarity: "very_rare" },
        { name: "고문 기구", file: "tortureApparatus.webp", rarity: "very_rare" },
        { name: "구울 대책국 사원증", file: "cCGIDCard.webp", rarity: "very_rare" },
        { name: "붉은 머리 왕지네", file: "redHeadedCentipede.webp", rarity: "very_rare" },
        { name: "야모리의 가면", file: "yamorisMask.webp", rarity: "ultra_rare" },
        { name: "핏빛 안대", file: "iridescentEyePatch.webp", rarity: "ultra_rare" }
    ],
    darkLord: [
        { name: "케르베로스의 발톱", file: "cerberusTalon.webp", rarity: "common" },
        { name: "시계탑 장비", file: "clockTowerGear.webp", rarity: "common" },
        { name: "루비색 화관", file: "rubyCirclet.webp", rarity: "common" },
        { name: "여행자의 모자", file: "travelersHat.webp", rarity: "common" },
        { name: "하얀 늑대 메달", file: "whiteWolfMedallion.webp", rarity: "uncommon" },
        { name: "날개달린 부츠", file: "wingedBoots.webp", rarity: "uncommon" },
        { name: "문스톤 목걸이", file: "moonstoneNecklace.webp", rarity: "uncommon" },
        { name: "마법의 티켓", file: "magicalTicket.webp", rarity: "uncommon" },
        { name: "피가 고인 고블릿", file: "bloodFilledGoblet.webp", rarity: "uncommon" },
        { name: "요정의 깃털", file: "sylphFeather.webp", rarity: "rare" },
        { name: "살인마 인형", file: "killerDoll.webp", rarity: "rare" },
        { name: "회중시계", file: "pocketWatch.webp", rarity: "rare" },
        { name: "메아리의 힘", file: "forceofEcho.webp", rarity: "rare" },
        { name: "선글라스", file: "sunglasses.webp", rarity: "rare" },
        { name: "와르그의 이빨", file: "wargsFang.webp", rarity: "very_rare" },
        { name: "조의 큐브", file: "cubeofZoe.webp", rarity: "very_rare" },
        { name: "메두사의 머리카락", file: "medusasHair.webp", rarity: "very_rare" },
        { name: "라피스 라줄리", file: "lapisLazuli.webp", rarity: "very_rare" },
        { name: "알루카드의 방패", file: "alucardsShield.webp", rarity: "ultra_rare" },
        { name: "핏빛 블라드의 반지", file: "iridescentRingofVlad.webp", rarity: "ultra_rare" }
    ],
    lich: [
        { name: "수정 구슬", file: "crystalBall.webp", rarity: "common" },
        { name: "트릭스터의 장갑", file: "trickstersGlove.webp", rarity: "common" },
        { name: "까마귀의 깃털", file: "ravensFeather.webp", rarity: "common" },
        { name: "너덜너덜한 머리띠", file: "tatteredHeadband.webp", rarity: "common" },
        { name: "유리 눈", file: "glassEye.webp", rarity: "uncommon" },
        { name: "드러남의 등불", file: "lanternofRevealing.webp", rarity: "uncommon" },
        { name: "주문 저장 반지", file: "ringofSpellStoring.webp", rarity: "uncommon" },
        { name: "염력 반지", file: "ringofTelekinesis.webp", rarity: "uncommon" },
        { name: "속도의 묘약", file: "potionofSpeed.webp", rarity: "uncommon" },
        { name: "화려한 뿔", file: "ornateHorn.webp", rarity: "rare" },
        { name: "요정의 망토", file: "cloakofElvenkind.webp", rarity: "rare" },
        { name: "속도의 부츠", file: "bootsOfSpeed.webp", rarity: "rare" },
        { name: "진주의 능력", file: "pearlOfPower.webp", rarity: "rare" },
        { name: "위축의 지팡이", file: "staffofWithering.webp", rarity: "rare" },
        { name: "보따리", file: "bagofHolding.webp", rarity: "very_rare" },
        { name: "투명 망토", file: "cloakofInvisibility.webp", rarity: "very_rare" },
        { name: "두 눈의 로브", file: "robeofEyes.webp", rarity: "very_rare" },
        { name: "용의 이빨로 만든 단검", file: "dragontoothDagger.webp", rarity: "very_rare" },
        { name: "카스의 검", file: "vorpalSword.webp", rarity: "ultra_rare" },
        { name: "핏빛 비열한 어둠의 책", file: "iridescentBookofVileDarkness.webp", rarity: "ultra_rare" }
    ]
};